// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlwqtgkodoaclyxntaws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sd3F0Z2tvZG9hY2x5eG50YXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzA5ODYsImV4cCI6MjA3MzM0Njk4Nn0.IpO3d-6dLqMk-UlRGwPXXmhRjuzgbF4sK9GeqHIzgq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});